stages:
  - deploy

lxc:
  stage: deploy
  image:
    name: code.home.jbeard.dev:5050/homelab/ansible/homelab-control/ansible-tool:latest
    entrypoint: ['']
  before_script:
    - set -a
    - cp $SSH_PRIVATE_KEY /home/ansible/.ssh/id_rsa && chmod 400 /home/ansible/.ssh/id_rsa
  script:
    - ansible-playbook -i inventory.ini -u deployer -b -l proxmox lxc.yml