collections:
  - name: https://code.home.jbeard.dev/homelab/platform/homelab-base.git
    type: git

roles:
  - src: marvinpinto.plex

  - src: https://code.home.jbeard.dev/homelab/ansible/jbeard.proxmox_lxc.git
    scm: git
    name: jbeard.proxmox_lxc
